import Head from "next/head";
import Link from "next/link";
import tw from "tailwind-styled-components";
import Map from "../components/Map";

export default function Home() {
  return (
    <Wrapper>
      <Head>
        <title>Uber clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Map />
      <ActionItems>
        <Header>
          <UberLogo src="https://i.ibb.co/84stgjq/uber-technologies-new-20218114.jpg" />
          <Profile>
            <Name>Ashish Sah</Name>
            <UserImage src="https://randomuser.me/api/portraits/lego/6.jpg" />
          </Profile>
        </Header>
        <ActionButtons>
          <Link href="/search">
            <ActionButton>
              <ActionButtonImage src="https://i.ibb.co/cyvcpfF/uberx.png" />
              Ride
            </ActionButton>
          </Link>
          <ActionButton>
            <ActionButtonImage src="https://i.ibb.co/n776JLm/bike.png" />
            2-wheeler
          </ActionButton>
          <ActionButton>
            <ActionButtonImage src="https://i.ibb.co/5RjchBg/uberschedule.png" />
            Reserve
          </ActionButton>
        </ActionButtons>
        <InputButton>Where to?</InputButton>
      </ActionItems>
    </Wrapper>
  );
}

const Wrapper = tw.div`flex flex-col h-screen`;

const ActionItems = tw.div`flex-1 p-4`;

const Header = tw.div`flex justify-between items-center p-5`;

const UberLogo = tw.img`h-11`;

const Profile = tw.div`flex items-center`;

const Name = tw.div`mr-4 w-20 text-sm`;

const UserImage = tw.img`h-12 w-12 rounded-full border border-gray-200 p-px`;

const ActionButtons = tw.div`flex space-x-5 my-2`;

const ActionButton = tw.div`bg-gray-200 flex-1 h-32 flex items-center flex-col justify-center rounded-lg transition transform hover:scale-105 duration-100 ease-out cursor-pointer text-xl`;

const ActionButtonImage = tw.img`h-3/5`;

const InputButton = tw.div`h-20 bg-gray-200 text-2xl p-4 flex items-center mt-5`;
